#!/usr/bin/env bash
frontend http_front
        bind *:80
        bind *:443 ssl crt /etc/haproxy/certs/www.26fzl.tech.pem
        redirect scheme https code 301 if !{ ssl_fc }
        default_backend my_backend

backend my_backend
        balance roundrobin
        server 390145-web-01 3.89.155.40:80 check
        server 390145-web-02 52.91.202.189:80 check
