#!/usr/bin/env bash
frontend http_front
        bind 54.234.94.223:80
        http-request add-header X-Forwarded-Proto http if !{ ssl_fc }
        http-request add-header X-Forwarded-Proto https if { ssl_fc }
        default_backend www-backend

frontend www-https
        bind 54.234.94.223:443 ssl crt /etc/letsencrypt/archive/www.26fzl.tech/fullchain1.pem
        http-request redirect scheme https unless { ssl_fc }
         http-request set-header X-Forwarded-Proto https
        default_backend  my_backend

backend my_backend
        balance roundrobin
        server 408319-web-01 3.89.155.40:80 check
        server 408319-web-02 52.91.202.189:80 check

backend letsencrypt-backend
    server letsencrypt 127.0.0.1:54321
