#!/usr/bin/env bash
# transfers a file from our client to a server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit;
fi

Path_to_file="$1";
Ip="$2";
Username="$3";
SSH_key="$4";

scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "$SSH_key" "$Path_to_file" "${Username}"@"${Ip}":~/
