#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

replace="servername ;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent ; "
sudo sed -i "s/servername ;/$replace/g" /etc/nginx/sites-available/default

sudo service nginx restart

sudo service nginx reload
